title: Priyaa Varshinee Srinivasan
url: "https://priyaasrini.github.io/"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: "https://github.com/priyaasrini"
footer_text: "Peace is a disarming concept :)"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "pvs_cv_2022.pdf"
 #- name: "Contact"
 #  link: "contact"

remote_theme: ankitsultana/researcher@gem
