title: Priyaa Varshinee Srinivasan
url: "https://priyaasrini.github.io/"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher/blob/gh-pages/README.md"
footer_text: "Website theme"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "pvs_cv_2022.pdf"
 #- name: "Contact"
 #  link: "contact"

remote_theme: ankitsultana/researcher@gem
